/**
 * Sentinel-X — Detection Types
 *
 * Matches the existing backend detection schemas:
 *   - Alert (generated by rule-based detection engine)
 *   - Rule  (detection rule configuration)
 *   - CorrelationResult (output of correlation engine)
 *   - AnomalyScore (output of ML anomaly service)
 *
 * These types match what the backend detection engine produces and
 * what any existing detection API endpoints return.
 */

import type { Severity } from "./event";

// ---------------------------------------------------------------------------
// Rule — matches backend Rule model
// condition is a JSON-serializable dict (tree of field/operator/value nodes)
// ---------------------------------------------------------------------------

export interface DetectionRule {
  id: string;
  name: string;
  description: string;
  condition: RuleCondition;
  severity: Severity;
  is_active: boolean;
  created_at?: string;
  updated_at?: string;
}

// ---------------------------------------------------------------------------
// Rule condition — tree structure used by the existing detection engine
// ---------------------------------------------------------------------------

export type RuleConditionOperator =
  | "equals"
  | "not_equals"
  | "contains"
  | "not_contains"
  | "in"
  | "not_in"
  | "and"
  | "or";

export interface SimpleCondition {
  field: string;
  operator: Exclude<RuleConditionOperator, "and" | "or">;
  value: string | number | boolean | string[];
}

export interface CompoundCondition {
  operator: "and" | "or";
  conditions: RuleCondition[];
}

export type RuleCondition = SimpleCondition | CompoundCondition;

// ---------------------------------------------------------------------------
// Alert — generated when a rule matches an event
// ---------------------------------------------------------------------------

export interface Alert {
  id: string;
  event_id: string;
  rule_id?: string;
  rule_name: string;
  severity: Severity;
  description?: string;
  created_at: string;
  acknowledged: boolean;
  acknowledged_at?: string | null;
  acknowledged_by?: string | null;
}

// ---------------------------------------------------------------------------
// Alert list response
// ---------------------------------------------------------------------------

export interface PaginatedAlerts {
  items: Alert[];
  total: number;
  page: number;
  size: number;
  pages: number;
}

export type AlertListResponse = Alert[] | PaginatedAlerts;

// ---------------------------------------------------------------------------
// Correlation result
// ---------------------------------------------------------------------------

export interface CorrelationResult {
  id?: string;
  rule_name: string;
  severity: Severity;
  event_ids: string[];
  description?: string;
  created_at?: string;
  metadata?: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// ML anomaly score
// ---------------------------------------------------------------------------

export interface AnomalyScore {
  event_id: string;
  score: number;           // 0.0 – 100.0 (or 0.0 – 1.0 per implementation)
  is_anomaly: boolean;
  threshold?: number;
  model_version?: string;
  evaluated_at?: string;
}

// ---------------------------------------------------------------------------
// Detection summary (for dashboard overview)
// ---------------------------------------------------------------------------

export interface DetectionSummary {
  total_alerts: number;
  open_alerts: number;
  critical_alerts: number;
  high_alerts: number;
  medium_alerts: number;
  low_alerts: number;
  rules_active: number;
  last_evaluated?: string;
}